### ISSUE TITLE
<style scoped>

### ISSUE THREAD

**Issue by cokoladasarizom** [FranckFreiburger/http-vue-loader#1]
Hi,

Can style in .vue file be scoped?
I tried adding scoped to your example, but .hello class was working even outside the component.
Am I missing something?

Mirko

**Comment by FranckFreiburger** [comment]
Hi Mirko,
I will try to implement this feature.

Franck.

**Comment by cokoladasarizom** [comment]
Thanks Franck.

By the way your loader works really great - it's a very useful piece of code!

Mirko

**Comment by FranckFreiburger** [comment]
Hi Mirko,
Let me know if my commit works for you.
Franck.

**Comment by cokoladasarizom** [comment]
Hi Franck,

This separates component style from the rest of the app just fine.

However in doesn't seem to separate scoped component styles other components.
For example .hello class in scoped style of my-component1 ideally could be separate from .hello class in scoped style in my-component2. 

Is it possible to contain scoped style on component only without it leaking into other component(s)?

Mirko

**Comment by FranckFreiburger** [comment]
Mirko,
currently, same components share same styles, can you give me an example where a component style is leaking in another ?

**Comment by cokoladasarizom** [comment]
Sorry, it was my mistake. Works great - thanks Franck!
