### ISSUE TITLE
How to use httpRequest

### ISSUE THREAD

**Issue by ernestchanjq** [FranckFreiburger/http-vue-loader#10]
I am running following in http-server 

However the following is working, but not the when i replace

```
 'my-component': httpVueLoader('my-component.vue')

 'my-component': httpVueLoader.httpRequest('my-component.vue')

```
I received following error:

> vue@2.3.4:440 [Vue warn]: Failed to mount component: template or render function not defined.
> 
> found in
> ---> <MyComponent>
>        <Root>

> `<!doctype html>
> <html lang="en">
>   <head>
>     <meta charset="utf-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
>     <meta name="theme-color" content="#000000">
> 
>     <title>Vue App</title>
>     <script src="https://unpkg.com/vue"></script>
>     <script src="https://unpkg.com/http-vue-loader"></script>
>     <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
>   </head>
>   <body>
>     <div id="my-app">
>       <my-component></my-component>
>     </div>
> 
>     <script type="text/javascript">
>       httpVueLoader.httpRequest = function(url) {
>           
>           return axios.get(url)
>           .then(function(res) {
>               console.log(res.data)
>               return res.data;
>           })
>           .catch(function(err) {
>               
>               return Promise.reject(err.status);
>           });
>       }
> 
> 
>       new Vue({
>         el: '#my-app',
>         components: {
>           'my-component': httpVueLoader('my-component.vue')
>         }
>       });
>     </script>
>   </body>
> </html>
> `
> 

```
<template>
    <div class="hello">Hello {{who}}</div>
</template>

<script>
module.exports = {
    data: function() {
        return {
            who: 'world'
        }
    }
}
</script>

<style>
.hello {
    background-color: #ffe;
}

```

**Comment by FranckFreiburger** [comment]
On my side, the following code seems to work properly:

```
<!doctype html>
<head>
	<title>Vue App</title>
	<script src="https://unpkg.com/vue"></script>
	<script src="https://unpkg.com/http-vue-loader"></script>
	<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<body>
	<div id="my-app"></div>
	<script type="text/javascript">
	  httpVueLoader.httpRequest = function(url) {
	      
	      return axios.get(url)
	      .then(function(res) {

	          return res.data;
	      })
	      .catch(function(err) {
	          
	          return Promise.reject(err.status);
	      });
	  }

	  new Vue({
	    el: '#my-app',
	    template: '<my-component></my-component>',
	    components: {
	      'my-component': httpVueLoader('./my-component.vue')
	    }
	  });
	</script>
</body>
```

maybe the main template is missing in your example ?

**Comment by ernestchanjq** [comment]
My mistake, My understanding of Vue mount is incorrect.
Thanks! Can closed the issue.

I missing the template: 
	<div id="my-app">
		<my-component></my-component>
	</div>
or
	 template: '<my-component></my-component>'
