### ISSUE TITLE
Needs to output error messages when .vue file script contains errors

### ISSUE THREAD

**Issue by ryangriggs** [FranckFreiburger/http-vue-loader#100]
This is an awesome library and apparently one of a kind.  The problem is that attempting to import a .vue file containing script errors renders only a ReferenceError: "responseText is not defined" error in the browser console, and does not give any indication of where the error(s) exists in the script.  This is basically a nightmare for debugging.  Please add a debug/development mode which outputs verbose error messages when the .vue file contains errors.  Or at the very least, point to the line number or give some sort of hint about why the script can't be loaded.

**Comment by SupremeSalvatore** [comment]
+1 For this feature or solution/workaround.
