### ISSUE TITLE
Unable to import/require scripts within .vue template file script

### ISSUE THREAD

**Issue by ryangriggs** [FranckFreiburger/http-vue-loader#101]
I am unable to import or require files within the .vue file <script> tag.

For example:
```
<script>
import { asdf } from './module.js'
```

or
```
<script>
var asdf = require('./module.js')
```

Both of these cause the module loading to fail, yielding only the following error in the browser console:

> ReferenceError: "responseText is not defined"
>     compile https://unpkg.com/http-vue-loader:168
>     compile https://unpkg.com/http-vue-loader:329
>     load https://unpkg.com/http-vue-loader:382
> vue-router.js:2119:19
>     abort https://unpkg.com/vue-router/dist/vue-router.js:2119
>     iterator https://unpkg.com/vue-router/dist/vue-router.js:2164
>     reject https://unpkg.com/vue-router/dist/vue-router.js:1937
>     once https://unpkg.com/vue-router/dist/vue-router.js:2002

**Comment by akauppi** [comment]
I think httpVueLoader needs Babel configuration, to work with ES modules. Have a look at https://github.com/FranckFreiburger/http-vue-loader/issues/89

**Comment by liuxiangyi86** [comment]
@ryangriggs how do you resolve this issue?
