### ISSUE TITLE
"Pending components loaded" event

### ISSUE THREAD

**Issue by dmikam** [FranckFreiburger/http-vue-loader#118]
Hi,

Shortly - it would be nice to have some kind of event/callback to trigger after all "pending" components are mounted.

Longer story: Usually, to execute something after all "pending" (not conditinal) application components are loaded  you would do something like this:

    const app = new Vue({....
        .....
        mounted: function(){
            this.$nextTick(function(){
                // gere gose code executed after ALL components are mounted
            });
        }

(here is the official doc describing this behaviour: [https://vuejs.org/v2/api/#mounted](https://vuejs.org/v2/api/#mounted))

But when you use httpVueLoader to load those components - this doesn't work anymore, so it would be greate to have something like this:

    const app = new Vue({....
        .....
        mounted: function(){
            httpVueLoader.allComponentsLoaded(function(){
                // gere gose code executed after ALL components are mounted
            });
        }

**Comment by FranckFreiburger** [comment]
Maybe vue3 will provide such feature.
see https://v3.vuejs.org/guide/migration/async-components.html#async-components
see https://github.com/vuejs/vue/issues/9416
