### ISSUE TITLE
How to user with vue-router

### ISSUE THREAD

**Issue by anardil** [FranckFreiburger/http-vue-loader#12]
Hello,

How to user with vue-router?

Thank you.

**Comment by anardil** [comment]
ping

**Comment by FranckFreiburger** [comment]
Hi,
http-vue-loader should work properly with VueRouter:

```
const router = new VueRouter({
  routes: [
    { path: '/', component: httpVueLoader('home.vue') },
    { path: '/foo', component: httpVueLoader('foo.vue') },
    { path: '/bar', component: httpVueLoader('bar.vue') }
  ]
})
```

**Comment by FranckFreiburger** [comment]
can I close this issue ?

**Comment by lixaotec** [comment]
Hello,

What about passing props? it seems not to recgnize

**Comment by davidmoseler** [comment]
This does not work. The page is blank and the DOM untouched. Please provide accurate instructions on how to use httpVueLoader with VueRouter.

**Comment by FullStackAlex** [comment]
@ghost 
It does work. Just got an app running without any issues.
