### ISSUE TITLE
Use Custom Components in Custom Components

### ISSUE THREAD

**Issue by OfficialCRUGG** [FranckFreiburger/http-vue-loader#124]
I think the title is pretty self-explanatory: How would I use CustomButton inside CustomNavbar for example?

I import CustomNavbar in the `index.html` File using:
```js
new Vue({
    el: "#root",
    components: {
        "custom-navbar": httpVueLoader("js/components/CustomNavbar.vue"),
    }
});
```
which by itself works. But now I want to use CustomButton inside the CustomNavbar File. How would I do this?

**Comment by Vkrj** [comment]
Import it inside the CustomNavbar.vue like this:

`<template>
	<custombutton></custombutton>
</template>

<script>
	
	module.exports = {
	
		components:{
			'custombutton': httpVueLoader('js/CustomButton.vue'),
		},

		data: function(){

			return {
				
			}

		},

	}

</script>
<style>

</style>`

Alternatively you can register the component globally using the **httpVueLoader.register()** method

**Comment by Vkrj** [comment]
Import it inside the CustomNavbar.vue like this:

```js
<template>
	<custombutton></custombutton>
</template>

<script>
	
	module.exports = {
	
		components:{
			'custombutton': httpVueLoader('js/CustomButton.vue'),
		},

		data: function(){

			return {
				
			}

		},

	}

</script>
<style>

</style>
```

Alternatively you can register the component globally using the **httpVueLoader.register()** method
