### ISSUE TITLE
Why run the example code has the unexpected error ?

### ISSUE THREAD

**Issue by chuanxd** [FranckFreiburger/http-vue-loader#13]
Vue version: v2.4.1
http-vue-loader: v1.3.1

Why run the example code has the unexpected error ?
But the view is current result.

![image](https://user-images.githubusercontent.com/4191668/28303381-7323c5de-6bc5-11e7-8488-c1e7c1f77f15.png)
![image](https://user-images.githubusercontent.com/4191668/28303383-761f835e-6bc5-11e7-9a3a-7ecdf9c10f36.png)

**Comment by FranckFreiburger** [comment]
Please give more details about how you load the vue file

**Comment by chuanxd** [comment]
@FranckFreiburger  my `index.html`
```html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/http-vue-loader"></script>
    <script src="/app.vue"></script>
  </head>

  <body>
    <div id="my-app">
      <app></app>
    </div>

    <script type="text/javascript">
      new Vue({
        el: '#my-app',
        components: {
          app: httpVueLoader('app.vue'),
        }
      });
    </script>
  </body>
</html>
```

**Comment by FranckFreiburger** [comment]
What do you expect to do with this line : ` <script src="/app.vue"></script>` ?
Note that `.vue` files are not script, they have to be processed before being used.
The vue file is loaded through `httpVueLoader('app.vue')`.

**Comment by chuanxd** [comment]
@FranckFreiburger 
sorry I am confuse the loader.
Thank you for your time.
