### ISSUE TITLE
Microsoft Edge CSS Scoping error

### ISSUE THREAD

**Issue by oscarjlep** [FranckFreiburger/http-vue-loader#15]
Edit - better title for issue, as it's only an Microsoft Edge -issue and not Internet Explorer 10/11 (sorry for the confusing title "Internet Explorer Edge", as such thing doesn't exist and leads to confusion).

When using Internet Explorer Edge, I'm getting following error when using "scoped" attribute for style. Apparently no error on IE11, Chrome or Firefox:

```
Vue warn]: Failed to resolve async component: function () {
			return new Component(name).load(url)
			.then(function(component) {
				
				return component.normalize();
			})
			.then(function(component) {
				
				return component.compile();
			})
			.then(function(component) {
				
				var exports = component.script !== null ? component.script.module.exports : {};
				
				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				return exports;
			})
		}
Reason: TypeError: Unable to get property 'setAttribute' of undefined or null reference
vue.js (440,7)

```

Index.html
```
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.3/vue.js"></script>
	<meta charset="UTF-8">
</head>
	<body>
		<div id="app">
			<board></board>
		</div>

		<script src="js/es6-promise.auto.min.js"></script>
		<script src="js/http-vue-loader.js"></script>
		
		<script>
			new Vue({
				el: '#app',
				components: { 
					'board': httpVueLoader('js/main-component.vue'),
				},
			});
		</script>
	</body>
</html>
```

main-component.vue
```
<template>
	<div class="board">
		test
	</div>
</template>

<script>
    module.exports = {
		data: function() {
			return {
			};
		}
    };
</script>

<style scoped>
.board {
	background: grey;
}
</style>
```

I traced error back to this line:
`this.template.getRootElt().setAttribute(this._scopeId, '');`

Apparently getRootElt return undefined on IE Edge ?

**Comment by oscarjlep** [comment]
Apparently an Edge bug:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11342645/

**Comment by FranckFreiburger** [comment]
edge issue 11342645, should already be handled in getRootElt(), see
```
getRootElt: function() {
	
	return (this.elt.content || this.elt).firstElementChild;
},
```

**Comment by FranckFreiburger** [comment]
please check in your network tab that `main-component.vue` is loaded properly

**Comment by oscarjlep** [comment]
Loading ok, but given return statement doesn't work due to edge-bug which I linked. 
this.elt.content is filled, but doesn't fetch firstElementChild. It apparently works on edge if replace with:
`return this.elt.content.childNodes[1];`

**Comment by oscarjlep** [comment]
Maybe(?) :

`return (this.elt.content || this.elt).firstElementChild || this.elt.content.childNodes[1];`

**Comment by FranckFreiburger** [comment]
I am unable to reproduce the issue on my IE11 (Trident/7.0 rv:11.0  on win7)

**Comment by FranckFreiburger** [comment]
what does (this.elt.content || this.elt) returns on your IE11 ?

**Comment by oscarjlep** [comment]
It returns correctly an object ({component: Object {...}, elt: HTMLUnknownElement {...}}), but it's the IE Edge which returns undefined.

**Comment by FranckFreiburger** [comment]
please test with `return (this.elt.content || this.elt).children[0]` instead of `childNodes[1]`

**Comment by oscarjlep** [comment]
```
return (this.elt.content || this.elt).children[0];

"Unable to get property '0' of undefined or null reference"
```

**Comment by oscarjlep** [comment]
![image](https://user-images.githubusercontent.com/26794513/28570058-0c4c70c4-7145-11e7-96a3-c0c67e1c0e06.png)

**Comment by FranckFreiburger** [comment]
I suppose that the following expression also fails:
`var tmp = window.document.createElement('template'); tmp.innerHTML = "<div id='foo'></div>"; tmp.children[0]` ?

**Comment by oscarjlep** [comment]
![image](https://user-images.githubusercontent.com/26794513/28570094-3329dc18-7145-11e7-886b-509367466e62.png)

Comparison between Edge (left) & Chrome (right):
![image](https://user-images.githubusercontent.com/26794513/28570187-a2846088-7145-11e7-9c2b-1ca118ec4955.png)

Apparently there are no firstElementChild, nor children - it's either because type of something different than in other browsers, or those methods could be inherited and hidden from tool tip. I'm not an expert on object debugging... Still, Edge find it by childNodes[1] (while node 0 was empty)

**Comment by FranckFreiburger** [comment]
what is your exact IE version and OS ?

**Comment by oscarjlep** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063

Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by FranckFreiburger** [comment]
lunchtime, see you later

**Comment by oscarjlep** [comment]
Sure - Meanwhile, I can confirm that the following works for me on every browser (IE11, Edge, latest Chrome, latest Firefox):

`return (this.elt.content || this.elt).firstElementChild || this.elt.content.childNodes[1];`

When using this statement, I'm able to check what this.elt.content contains (element = this.elt.content), and I get following output:

![image](https://user-images.githubusercontent.com/26794513/28570587-7491da1e-7147-11e7-9cb6-df42d4a7d139.png)

For some reason firstElement is emptyTextNode, but this is probably bug as stated on MS Edge ticket which is still unresolved.

**Comment by FranckFreiburger** [comment]
the issue should be fixed, let me know if it is ok

**Comment by oscarjlep** [comment]
Confirmed fixed, thanks!
