### ISSUE TITLE
Failed to resolve async component when using newest http-vue-loader version

### ISSUE THREAD

**Issue by Vergil0327** [FranckFreiburger/http-vue-loader#19]
Hi I'm new to vue.js.
I got error & I don't know how to resolve
this is how I use http-vue-loader, and I put my components in

public/components/test/a.vue
public/components/test/b.vue
----------------------------------------------------

Vue.use(httpVueLoader);

new Vue({
    components: {
      'a': httpVueLoader('/components/test/a.vue'),
      'b': httpVueLoader('/components/test/b.vue'),
    }, ...

----------------------------------------------------
with
<script src="https://unpkg.com/http-vue-loader@1.3.2"></script>   -> It works !
<br>
<script src="https://unpkg.com/http-vue-loader"></script> (newest version)   -> it failed to load components & show error

vue.js:485 [Vue warn]: Failed to resolve async component: function () {

			return new Component(name).load(url)
			.then(function(component) {
				
				return component.normalize();
			})
			.then(function(component) {
				
				return component.compile();
			})
			.then(function(component) {
				
				var exports = component.script !== null ? component.script.module.exports : {};
				
				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				return exports;
			})
		}
Reason: TypeError: url.substr is not a function

WHY IT TELL ME  I GOT A TYPE ERROR ?

**Comment by FranckFreiburger** [comment]
Please provide a minimal exemple that reproduce the issue.

side note:
`Vue.use(httpVueLoader);` is only needed when you load your components with `'url:/components/test/a.vue'`

**Comment by Vergil0327** [comment]
version 1.3.2  --> it works
this is my html 


```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="/vendor/jquery/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/http-vue-loader@1.3.2"></script>
  </head>
  <body class="page-inner">

    <div id="contentPage"></div>

  </body>
  <script type="text/x-template" id="contentPage-template">
    <div>
      <test-a :type="type"
            :pageTitle="pageTitle"
            :locale="locale"
            :startTime="startTime"
            :endTime="endTime"
            :templateHedFot="templateHedFot"
            :path="path"
            :meta="meta"
            :pathErr="pathErr"
            :isPageMode="type === 'page'"></test-a>
    </div>
  </script>

<script>

  // http-vue-loader
  Vue.use(httpVueLoader);

  var defaultData = {
    step: 'create',
    path: '',
    type: 'page',
    locale: 'en',
    meta: [{content: '', itemprop: '', name: '', property: ''}],
    pathErr: '',
    templateHedFot: 'default',
    startTime: '',
    endTime: '',
    pageTitle: '',
  };

  // Vue entry point
  var $contentPage = new Vue({
    el: "#contentPage",
    template: '#contentPage-template',
    components: {
      'test-a': 'url:/components/cms/testA.vue',
    },
    delimiters: ['<%', '%>'],
    data: function() {
      return defaultData;
    },
    computed: {

    },
    methods: {
    },
    mounted() {
    },
  });
</script>
  </body>
</html>
```
--------------
But with latest version (`<script src="https://unpkg.com/http-vue-loader"></script>`), it failed

and pops up error!



```
vue.js:485 [Vue warn]: Failed to resolve async component: function () {

			return new Component(name).load(url)
			.then(function(component) {
				
				return component.normalize();
			})
			.then(function(component) {
				
				return component.compile();
			})
			.then(function(component) {
				
				var exports = component.script !== null ? component.script.module.exports : {};
				
				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				return exports;
			})
		}
Reason: TypeError: url.substr is not a function
```

**Comment by Vergil0327** [comment]
version 1.3.2  --> it works
this is my html & I also use http-vue-loader in my nested component


```
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/http-vue-loader@1.3.2"></script>
  </head>
  <body>

    <div id="contentPage"></div>

  </body>
  <script type="text/x-template" id="contentPage-template">
    <div>
      <test-a></test-a>
    </div>
  </script>

    <script>

      // http-vue-loader
      Vue.use(httpVueLoader);

      var defaultData = {
        step: 'create',
      };

      // Vue entry point
      var $contentPage = new Vue({
        el: "#contentPage",
        template: '#contentPage-template',
        components: {
          'test-a': 'url:/components/cms/testA.vue',
        },
        data: function() {
          return defaultData;
        },
        computed: {

        },
        methods: {
        },
        mounted() {
        },
      });
    </script>
  </body>
</html>

```
--------------
But with latest version (`<script src="https://unpkg.com/http-vue-loader"></script>`), it failed

and pops up error!



```
vue.js:485 [Vue warn]: Failed to resolve async component: function () {

			return new Component(name).load(url)
			.then(function(component) {
				
				return component.normalize();
			})
			.then(function(component) {
				
				return component.compile();
			})
			.then(function(component) {
				
				var exports = component.script !== null ? component.script.module.exports : {};
				
				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				return exports;
			})
		}
Reason: TypeError: url.substr is not a function
```

--------
And this is test-a component

```
<template>

<div>
  <div>hello world</div>
  <test-b></test-b>
</div>
</template>
<script>

Vue.use(httpVueLoader);

module.exports = {

  components: {
    'test-b': 'url:/components/cms/testB.vue',
  },
  data() {
    return {

    }
  },
  watch : {

  },
  computed: {
  },
  methods: {
  },
  mounted() {

  }
}
</script>

<style scoped>

</style>
```

And this is test-b component

```
<template>

<div>
  <div>hello testB</div>
</div>
</template>
<script>

Vue.use(httpVueLoader);

module.exports = {

  props: {

  },
  data() {
    return {

    }
  },
  watch : {

  },
  computed: {
  },
  methods: {
  },
  mounted() {

  }
}
</script>

<style scoped>

</style>
```

**Comment by FranckFreiburger** [comment]
`Vue.use(httpVueLoader);` must be called only once, in the main script.

**Comment by ameibj** [comment]
I'm sure I used the HttpVueLoader in your tutorial to install  Vue. use (httpVueLoader). The problem is that I don't have a problem with the version in May 2017, but the current version will prompt the same error (same error code location).
Also, how can I refer to your example using LESS in a single file VUE component? I hope I can express your understanding. Thank you very much! Ps: I am not good at English, excuse me!

**Comment by FranckFreiburger** [comment]
Feel free to reopen the issue if the problem persists.

**Comment by sjkoning** [comment]
This is indeed still an issue!

I've literally copied your two example files (index.html and my-component.vue) from the README and it gives this error.

**Comment by Harlekuin** [comment]
If you're using the README example - make sure the my-component.vue file is in the right location

**Comment by 275761919** [comment]
The same problem!

**Comment by sdenni** [comment]
me too, got same problem~

**Comment by ElephantsFoot** [comment]
got same problem

**Comment by andrebaldo** [comment]
Please check if your vue component is declared using the syntax bellow:
```
<script>
    module.exports =  {
    ...
  }
</script>
```
Rather than :
```
<script>
    export default  {
    ...
  }
</script>
```
@ElephantsFoot, @sdenni

**Comment by anyjaim** [comment]
Possible solution: remove the Lang attribute from the tags: template and style. I had a hard time finding this simple error. That's for using snippets
