### ISSUE TITLE
请问 less 应该如何处理！

### ISSUE THREAD

**Issue by ameibj** [FranckFreiburger/http-vue-loader#20]
<script src="//stylus-lang.com/try/stylus.min.js"></script>
<script src="httpVueLoader.js"></script>
<script>
httpVueLoader.langProcessor.stylus = function(stylusText) {
    return new Promise(function(resolve, reject) {
        stylus.render(stylusText, {}, function(err, css) {
            if (err) reject(err);
            resolve(css);
        });
    })
}
</script>
这个例子是 stylus 的 。 Less 如何修改？  另外还有如果想直接 把vue后缀的 单文件组件ES6 JS  转为ES5 有没有方法？ 非常感谢，这2个问题能解答一下？ 谢谢！谢谢!

**Comment by FranckFreiburger** [comment]
Please use English language.

**Comment by ameibj** [comment]
This example is stylus.Question 1. How does Less modify this example?Question 2. Is there any way to convert the ES6 grammars of the Vue suffix to ES5 syntax directly?Thank you very much. Can you answer these two questions?Thank you very much!Thank you very much!

**Comment by ameibj** [comment]
In addition, the current latest httpVueLoader (1.3.3) version, when the parent component introduces a subcomponent, the data for the subcomponent request.The browser will make a mistake.Replacing the old version of May 2017 is not a problem.
Failed to resolve async component: function () {

		return new Component(name).load(url)
		.then(function(component) {
			
			return component.normalize();
		})
		.then(function(component) {
			
			return component.compile();
		})
		.then(function(component) {
			
			var exports = component.script !== null ? component.script.module.exports : {};
			
			if ( component.template !== null )
				exports.template = component.template.getContent();

			if ( exports.name === undefined )
				if ( component.name !== undefined )
					exports.name = component.name;

			return exports;
		})
	}

**Comment by FranckFreiburger** [comment]
Please have a look at this issue: https://github.com/FranckFreiburger/http-vue-loader/issues/19#issuecomment-320590214
If that does not solve your issue, please give me more details about your issue.

You can use babel to transpile ES6 to ES5 (try https://github.com/babel/babel-standalone)

untested code:
```
httpVueLoader.langProcessor.coffee = function(scriptText) {
  return Babel.transform(scriptText, { presets: ['es2015'] }).code;
}
```

**Comment by ameibj** [comment]
I'm very sorry, but I have a correct position! The error is in my reference and rewriting the following JS!
< script SRC = "libs/js/less. Js" > < / script >
HttpVueLoader. LangProcessor. Less = function (lessText) {
Return new Promise (function (resolve, reject) {
Less. Render (lesssText, {}, function (err, CSS) {
If (err) reject (err);
Resolve (CSS);
});
})
}
< style lang = "less" >... < / style >

**Comment by ameibj** [comment]
Hello, I haven't found the modification based on your stylus example. Can you write a method based on LESS preprocessor?

**Comment by ameibj** [comment]
A single file component vue file, which is written in the example above, is generated to the HTML page and the browser renders the return of an Object Object, without the LESS escape being the CSS style

<style lang="less">
    .el-menu-vertical-demo {
        .el-submenu__title {
            background-color: red
        }
    }
</style>

**Comment by ameibj** [comment]
A single file component vue file, which is written in the example above, is generated to the HTML page and the browser renders the return of an Object Object, without the LESS escape being the CSS style

<style lang="less">
    .el-menu-vertical-demo {
        .el-submenu__title {
            background-color: red
        }
    }
</style>

**Comment by pulipulichen** [comment]
The css variable from less render's result is an object. The CSS script is in css's "css" attribute.
Following code is work:

````js
httpVueLoader.langProcessor.less = function (lessText) {
  return new Promise (function (resolve, reject) {
    less.render(lessText, {}, function (err, css) {
      if (err) reject (err);
      resolve(css.css);
    });
  })
}
````
