### ISSUE TITLE
can i use this to compile vue file to js file?

### ISSUE THREAD

**Issue by yoyoys** [FranckFreiburger/http-vue-loader#21]
can i use this to compile vue file to js file?
It means convert vue file to es5 render function.
i think this will be faster in production.

**Comment by manatlan** [comment]
interested too !

**Comment by FranckFreiburger** [comment]
@yoyoys , you can use httpvueloaderlangprocessor (https://github.com/FranckFreiburger/http-vue-loader#httpvueloaderlangprocessor) to transpile from es6 to es5.
