### ISSUE TITLE
Next Tick fails

### ISSUE THREAD

**Issue by galipmedia** [FranckFreiburger/http-vue-loader#23]
```
module.exports = {
mounted: function () {
  this.$nextTick(function () {
    // Code that will run only after the
    // entire view has been rendered
  })
}
}
```
 [Vue warn]: Failed to resolve async component: function() {

Unfortunately this is causing this error for me. Any idea how to get $nextTick working?

**Comment by FranckFreiburger** [comment]
please give a more complete example that raises the error.
