### ISSUE TITLE
Suport other extension ".html" for allowing syntaxhiglight in Plunker

### ISSUE THREAD

**Issue by jpeter06** [FranckFreiburger/http-vue-loader#24]
Hello Franck,
First thanks for your loader. Works wonderfull. :-)
I have one simple request that I think  can make sense. Allow the extension ".html" in vue files.
I use this loader  in Plunker. I use to create the Vue files with ".html" extension so that I can fully use the syntax highlight of plunker (.vue extensión files are not yet highlighted), but now http-vue-loader only supports ".vue" extensions.

thanks again.

**Comment by FranckFreiburger** [comment]
off topic, you should try to solve this issue in an other way
