### ISSUE TITLE
Minor wish: support for url-parameters

### ISSUE THREAD

**Issue by oscarjlep** [FranckFreiburger/http-vue-loader#25]
I have an issue with web-server / framework cache not refreshing as often as I'd like to. I would be perfectly fine with having daily cache-flush, which is easy to enable by writing:

`'editor': httpVueLoader(LR.contextPath + '/js/views/event/editor.vue?ts=' + moment().format('DDMMYYYY')),`

Basically browser cache would be skipped when timestamp-parameter changes. For some reason these parameters are parsed away by httpVueLoader, so that it always ends fetched url to be "something/something.vue", without questionmark  & parameters. What changes would be needed in order to support url-parameters, and what is the original reason for parsing 'em out?

**Comment by oscarjlep** [comment]
Hi,

thanks for noticing this! I'v been successfully using this plugin for few months now and it has proved to be great support for my project. Still, this caching issue has proved to be an nuisance. Even when developing components which rely on components it seems that those inner .vue gets are being cached, so I have to use force-refresh -action by having multiple tabs open (which each target individual .vue source-files). I think this problem could be avoided by using few guidelines while developing (such as var devMode = true, which would control what kind of timestamp variable would be used - daily or per second).

**Comment by oscarjlep** [comment]
As for now, I fixed this by simply overwriting one line of code:

`	function parseComponentURL(url) {

		var comp = url.match(/(.*?)([^/]+?)\/?(\.vue)?(?:\?|#|$)/);
		return {
			name: comp[2],
			url: comp.input
			//url: comp[1] + comp[2] + (comp[3] === undefined ? '/index.vue' : comp[3])
		};
	}`

Would you happen to see any problem by using comp.input instead of building it from pieces? I simply couldn't figure that regexp and how to enable all the parameters on split-results. It seemed to me that comp.input did point to correct path, be it root or sub-path on server.

**Comment by FranckFreiburger** [comment]
Can you try with:

```
	function parseComponentURL(url) {

		var comp = url.match(/(.*?)([^/]+?)\/?(\.vue)?(\?.*|#.*|$)/);
		return {
			name: comp[2],
			url: comp[1] + comp[2] + (comp[3] === undefined ? '/index.vue' : comp[3]) + comp[4]
		};
	}
```

thanks

**Comment by oscarjlep** [comment]
Seems to work well. What's the difference between using simply the input vs one with regexp-parsing?

**Comment by FranckFreiburger** [comment]
the idea is to support `index.vue` when the vue file name is omitted.
`parseComponentURL('http://www.test.com/app')`
returns: `{name: "app", url: "http://www.test.com/app/index.vue"}`
