### ISSUE TITLE
quickfix: add support to vue.html

### ISSUE THREAD

**Issue by MosheL** [FranckFreiburger/http-vue-loader#28]
Hi!

I was modified the `url` regex to use a static HTML file for vue (as  some HTTP Server configurations has a restrictive list of extensions working)

     var comp = url.match(/(.*?)([^/]+?)\/?(\.vue)?(\?.*|#.*|$|.html$)/);

for example:

	new Vue({
			el: '#my-app',
			components: {
				'my-component': httpVueLoader('App.vue.html')
			}
		});

This also useful for  code coloring in  vue-less IDE's.

**Comment by FranckFreiburger** [comment]
duplicate with #24
