### ISSUE TITLE
Not able to load .vue file from folder above

### ISSUE THREAD

**Issue by tobiratzberger** [FranckFreiburger/http-vue-loader#29]
It's not possible to include an .vue file if the folder is not in the same direction!

Would it be possible to support something like this?

      new Vue({
        el: '#my-app',
        components: {
          'my-component': httpVueLoader('../test/my-component.vue')
        }
      });

**Comment by DrSensor** [comment]
Maybe try using uri pattern and absolute path 
`httpVueLoader('file://<project path>/test/my-component.vue')`

**Comment by FranckFreiburger** [comment]
relative URLs are supported, make sure that `../test/my-component.vue` is publicly available from the current directory.
