### ISSUE TITLE
Is it possibile the call recursive?

### ISSUE THREAD

**Issue by aasci** [FranckFreiburger/http-vue-loader#32]
Hi,
i write the example:
index.html
<html lang="en">
  <head>
    <script src="vendor/vue.js"></script>
    <script src="vendor/http-vue-loader.js"></script>
  </head>

  <body>
    <div id="my-app">
      <my-component></my-component>
    </div>

    <script type="text/javascript">
      new Vue({
        el: '#my-app',
        components: {
          'my-component': httpVueLoader('my-component.vue')
        }
      });
    </script>
  </body>
</html>

my-component.vue

<template>
    <div class="hello">Ciao {{who}}!</div>
	<my-component-2></my-component-2>
</template>

<script>
module.exports = {
	components: {
          'my-component-2': httpVueLoader('my-component-2.vue')
    },
    data: function() {
        return {
            who: 'mondo'
        }
    }
}
</script>

my-component-2.vue

<template>
    <div class="hello">Ciao 2 {{who}}!</div>
</template>

<script>
module.exports = {
    data: function() {
        return {
            who: 'mondo-2'
        }
    }
}
</script>

[ERROR]
Error compiling template:
- Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

Why?

Thanks

**Comment by dennythecoder** [comment]
Can you include the templates?  If the error is in compiling the template, it'll help to take a look at the actual templates.   My bet is that there's a syntax error at some point... something I've done personally :-)

**Comment by aasci** [comment]
you're right, thanks!
