### ISSUE TITLE
Is it possible to require/import?

### ISSUE THREAD

**Issue by langdonx** [FranckFreiburger/http-vue-loader#38]
I've been using httpVueLoader for a side project where I just don't need a compile step and it's been very convenient!

As the app has been getting more complex, I've been wanting to modularize some parts, but `require` doesn't seem to work inside of a `.Vue` file's `script` block.  I'm assuming it's not supported, but sort of hoping I'm just doing it wrong...

```
<script>
var mixins = require('./test.js');

module.exports = {
    mixins,
});
</script>
```

Nothing actually breaks, but `./test.js` doesn't get loaded and my mixins don't get executed.

**Comment by dshastry** [comment]
Would the PR @sathomas is mentioning offer a resolution to imports not working as well?

I'm running Vue 2.5.16 and using VueHTTPloader (no node). I'm trying to use the [Vue-Fuse component ](https://github.com/shayneo/vue-fuse) but it's failing because of the import statement. 

Here's the specific line that breaks it:

`import Fuse from "./fuse.min.js"`

The import results in this error:
```

[Vue warn]: Failed to resolve async component: function() {

			return new Component(name).load(url)
			.then(function(component) {

				return component.normalize();
			})
			.then(function(component) {

				return component.compile();
			})
			.then(function(component) {

				var exports = component.script !== null ? component.script.module.exports : {};

				if ( component.template !== null )
					exports.template = component.template.getContent();

				if ( exports.name === undefined )
					if ( component.name !== undefined )
						exports.name = component.name;

				exports._baseURI = component.baseURI;

				return exports;
			});
		}
Reason: SyntaxError: Unexpected identifier

```

**Comment by dshastry** [comment]
Thanks for the quick response @FranckFreiburger. I followed your advice and set it up as mentioned. Still getting a "not an error in mounted hook: Fuse is not a constructor" error. Also looked into #36 and leveraged some concepts from there. What do you think I'm doing wrong? Code below:

in my index.php file:

`<script src="assets/js/babel.min.js" type="text/javascript"></script>
	<script src="assets/js/vue.loader.js" type="text/javascript"></script>
<script>
		httpVueLoader.langProcessor.babel = script => Babel.transform(script, { presets: ['es2017', 'stage-3'] }).code;
	</script>
`

in my cr-fuse component:
`<script lang="babel">
	var Fuse = require('../dependencies/scripts/fuse.min.js');
	
module.exports = {
	Fuse,
// other component parameters
`

The directory structure here is:
components
     cr-table.vue (this calls cr-fuse.vue)
     dependencies
          scripts
               fuse.min.js
     mixins
          cr-fuse.vue

**Comment by PwntasticKev** [comment]
Hello from the future! I'm a bit new to the vue/php world and am using your library to import components in. 
Is there any new feature allowing the es6 support for importing libraries? I'm guessing it could be more along the php/babel side not being able to compile things correctly.
