### ISSUE TITLE
module.exports may be a promise.

### ISSUE THREAD

**Issue by trueromanus** [FranckFreiburger/http-vue-loader#45]
In features list has point - module.exports may be a promise.
Sorry if I my question will be odd but what this mean and how this works.
I try
```javascript
module.exports = async function () {
    const aaa = await bbb();
    return {
       data() {
            return {};
       }
    }
}
```
but this not works. Can you comment on how I can use this feature.

**Comment by FranckFreiburger** [comment]
fixed in v1.3.6 (issue #54)
