### ISSUE TITLE
Blank nested router view when refreshed

### ISSUE THREAD

**Issue by alvindimla** [FranckFreiburger/http-vue-loader#48]
Hi,

I managed to create a nested router view using httpvueloader, and its working great.
But when I tried to refresh it or open the link in a new tab, its just blank.  (params)

On console it says:
`Failed to mount component: template or render function not defined.`

This was not the case when I created a nested router view using pure JS files. Am I missing something here?

On firefox console:
`XML Parsing Error: prefix not bound to a namespace
Location: http://localhost:8080/app-vue/dashboard/src/components/routes/projects.vue
Line Number 9, Column 25:

[Vue warn]: Failed to mount component: template or render function not defined.`

**Comment by alvindimla** [comment]
Additional: Even if there's no nested router-view, the children route will always be blank when refreshed or opened in a new tab.

**Comment by FranckFreiburger** [comment]
Can you provide a minimal test case ?
