### ISSUE TITLE
<style lang="sass"> / httpVueLoader.langProcessor.scss error

### ISSUE THREAD

**Issue by FinnProjects** [FranckFreiburger/http-vue-loader#52]
I'm getting an error while trying to use httpVueLoader.langProcessor.scss
I used the README.md example

![sass](https://user-images.githubusercontent.com/25557084/45591342-94bb5180-b926-11e8-9fbb-3cb644dd138f.png)

**Comment by sp00x** [comment]
That sounds like you haven't registered 'scss' with the langProcessor attribute as described?

( the `httpVueLoader.langProcessor.scss = function (scssText) { ..` part of the example)

**Comment by chasebank** [comment]
@FranckFreiburger Is there an actual example of this working somewhere? I haven't been able to get it working. The docs seem a little unclear.
