### ISSUE TITLE
Global registration

### ISSUE THREAD

**Issue by giolvani** [FranckFreiburger/http-vue-loader#53]
There some way to register these components globally?

Something like:
```javascript
Vue.component('my-component-name', httpVueLoader('./path/file.vue'))
```
It would be very useful for components that are used in all views.

**Comment by lixaotec** [comment]
@giolvani I manage to accomplish as you´ve mentioned.

Check if you are exporting module correctly. module.exports = {} ..

**Comment by giolvani** [comment]
Yes, I am...

**Comment by lixaotec** [comment]
What is the issue then? Can you provide more details?

Thanks.

**Comment by annymosse** [comment]
i think there is no problem he had ,it's only info :relaxed:

**Comment by giolvani** [comment]
Sorry for delay, guys...

I really don´t know why, but it is working for now...

thanks
