### ISSUE TITLE
Failed to Resolve Async Component

### ISSUE THREAD

**Issue by friedforest** [FranckFreiburger/http-vue-loader#56]
Sorry if this is a dumb question, but I kept getting error saying "[Vue warn]: Failed to resolve async component:"
![screen shot 2018-11-09 at 10 31 33 pm](https://user-images.githubusercontent.com/32941345/48297139-4d0cfe00-e46f-11e8-952a-4afd6ab75a1a.png)

I'm trying to build a simple file reader, here is my code:

// scr/main.js
new Vue({
  el: '#app',
  components: { 
    'App': httpVueLoader('scr/App.vue') 
  },
  template: '<App/>'
});

// scr/App.vue
<template>
  <div id="app">
    <reader v-bind:flowers="workInfo"></reader>
  </div>
</template>

<script>
import Reader from './components/Reader';

export default {
  name: 'App',
  components: {
    Reader
  },
  data() {
    return {
      workInfo: [
        {
          title: 'Lorem Ipsum',
          author: 'Lorem Ipsum'
        },
        {
          title: 'Lorem Ipsum',
          author: 'Lorem Ipsum'
        },
        {
          title: 'Lorem Ipsum',
          author: 'Lorem Ipsum'
        }
      ]
    };
  }
};
</script>

Thank you very much for helping!

**Comment by FranckFreiburger** [comment]
Your component uses `import / export`, and this is not supported by http-vue-loader.
Use `require/ module.exports` instead.

**Comment by friedforest** [comment]
> Your component uses `import / export`, and this is not supported by http-vue-loader.
> Use `require/ module.exports` instead.

got it thanks

**Comment by Kraloz** [comment]
I'm recieving the same error but I'm not using node (so I can't _module.exports_).
 How can I replace the 
`
<sciprt>
export default {
...
}` 
part from my component?
P.S. I'm very new to Vue
Thank you for your time!

**Comment by timoteo7** [comment]
have some exemple of how to use **_REQUIRE_** ?
i only can use yet in **Template**:
```
<component :is="helloworld"/>`
```
and in **Script**:
```
module.exports =  {
    computed: {
      helloworld: function () { return window.httpVueLoader('components/HelloWorld.vue'); }
    }
}
```
have some better way ?

**Comment by anyjaim** [comment]
Possible solution: remove the Lang attribute from the tags: template and style. I had a hard time finding this simple error. That's for using snippets
