### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by Eduard-gan** [FranckFreiburger/http-vue-loader#64]
Hi, great project! I'm curious why you not recommend it for production?

**Comment by FranckFreiburger** [comment]
It is not recommended in production because it much less powerful as vue-loader + webpack.
However, if it fits your requirements, it is ok, but I really encourage people to use vue-loader + webpack.

**Comment by Eduard-gan** [comment]
Thanks for the answer. In my case integrating webpack node and all of their dependencies into project deployment will bring a great overhed to the project maintenance cost just because of literally two-three simple vue widgets which share subcomponents with each other. Thats why i searched a solution to that problem and found this project.

Btw personally i think that your project shouldn't be labeled as "testing-only" if it's stable and maintained but just not so feature reach as webpack with its loaders. :) Someone could probably not recommend a cat utility for production because of MS Office existance :))) Anyway, thank you for this great work, it's awesome.

**Comment by FranckFreiburger** [comment]
thanks :)
