### ISSUE TITLE
Example Incomplete

### ISSUE THREAD

**Issue by acklenx** [FranckFreiburger/http-vue-loader#7]
None of the examples appear complete.  It doesn't seem as though that much is missing from the snippets... except that I can't get it to work.  I tried it my code first (foolishly).  I have a "full" example of the html that I am using.  I'm using your my-component.vue example unmodified - since it seemed complete.  Is there an error in the sample code, or is it something I messed up when filling in blanks? 

```
<!doctype html>
<html lang="en">
	< head>
		<script src="https://unpkg.com/jquery@3.2.1"></script>
		<script src="https://unpkg.com/vue@2.3.3"></script>
		<script src="https://unpkg.com/es6-promise@4.1.0"></script>
		<script src="https://unpkg.com/http-vue-loader@1.3.1"></script>
	</head>

	<body>
		<my-component></my-component>
		<!-- More Javascript -->
		<script type="text/javascript">

			new Vue( {
				components: {
					'my-component': httpVueLoader( 'my-component.vue' )
				}
			} );

		</script>
	</body>
</html>
```

**Comment by FranckFreiburger** [comment]
here is a full but minimalist example:

*my-component.vue*
```vue
<template>
  <div class="hello">Hello {{who}}</div>
</template>

<script>
module.exports = {
  data: function() {
    return {
      who: 'world'
    }
  }
}
</script>

<style>
.hello {
  background-color: #ffe;
}
</style>
```


*index.html*
```html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/http-vue-loader"></script>
  </head>

  <body>
    <div id="my-app">
      <my-component></my-component>
    </div>

    <script type="text/javascript">
      new Vue({
        el: '#my-app',
        components: {
          'my-component': httpVueLoader('my-component.vue')
        }
      });
    </script>
  </body>
</html>
```

since some browsers do not allow XMLHttpRequest to access local files (`Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https`).
Yo can start a small express server to run this example.

`npm install express`
`npm install serve-static`

*server.js*
```js
var path = require('path');
var express = require('express');
var serveStatic = require('serve-static');

var app = express();
app.use(serveStatic(__dirname, {'index': 'index.html'}));
app.listen(8181);
```

`node server`

**Comment by acklenx** [comment]
Brilliant!  That works.  I was running a server, but that is very nice to call out the CORS restriction, that easily could have tripped me up.  Being new I just wasn't sure what was required/missing, and going from example to example it's easy to miss a detail.  I did try converting a more complete vue component that I wrote, but in the rewrite I missed the pound (#) in the el identifier.  Thank you very much for the example.  

Might I suggest (via pull request if you prefer) to include your full example for us noobs in your readme?  You could then keep the deltas you already have for each of the different ways to use your loader.  I think it would be helpful.  Not a big deal, people can now find the example in the issues section. Just a thought.

I really like this loader.  If fills a huge gap for small to medium sized projects/prototypes .  I want my components in separate files, but I don't want to build (or download an extra 39MB! of cli just to see my changes).  For a _less_ opinionated framework, Alex chose and odd place to be very opinionated.

Thanks again

Quincy
