### ISSUE TITLE
Any way to debug?

### ISSUE THREAD

**Issue by jmbldwn** [FranckFreiburger/http-vue-loader#70]
The script portion of the .vue file doesn't show up anywhere in the chrome debugger that I can see, and I would really like to place a breakpoint in there.  

Any suggestions?

**Comment by jmbldwn** [comment]
OK, for anyone else interested, here's the trick:  Each .vue file ends up in a virtual module in Chrome with a name like VM1234:56.  To easily find the module my .vue file ends up as, I simply add a log entry from the create() trigger:

```    
created() {
        console.log('created: <moduleName>.vue');
    }
```
Then after loading my app in Chrome, I find the log output and click on the handy link on that line that takes me to the code, where I can add breakpoints, inspect, everything I need.  Yay.

**Comment by 3rdSenna** [comment]
@jmbldwn , thanks for that suggestion of log on create. It helps.
I also found out that you can add "debugger;" on the create (or any other event) and the break point will be triggered once hits it.

```
mounted: function () {  
   debugger;
}

```
I'd like to find a better way solution to it. 
I can see in "httpVueLoader.min.jh" a comment saying
//# sourceMappingURL=/sm/5bc5a8b811dd61216db976e3d9609396d245132c5b0f895820e89deeadefef88.map

My hope is to use it to map the file "VM123:45" created on fly with my actual Component.vue.
I'm trying to figure out how to use it.

I'd like to debug through my VSCode without adding "debugger" all the time.

**Comment by 3rdSenna** [comment]
SORTED!
The currently app that I'm working there's no build step, so I only upload the Folder/Files to my server. So I've static path and file name. 
Saying it, here's the setup that solved my problem.

on VSCode 

`launch.json`
```
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Chrome",
      "url": "https://mySite.com/",
      "webRoot": "${workspaceFolder}/",
      "sourceMaps": true
    }
  }
```
The key part here is the "sourceMaps: true"

`${workspaceFolder}/components/myComponent.vue`
```

<template>
  <div >
    Hellowwwwww Uordi!
  </div>
</template>

<script>
//# sourceURL=/components/myComponent.vue
module.exports = {
  name: "myComponent",
  methods: {
    myEvent: function() {
      console.log("AE: myEvent", myEvent) 
    }
  }
}
</script>

```
The key part in here was setting "//# sourceURL=/components/myComponent.vue". 
That's how the mapping will track which file is the actual component. 

Run your app, then the component is registered, you can simply add the breakpoint. Before it get registered it didn't work for me.

![image](https://user-images.githubusercontent.com/32235364/68123888-fdd49e80-ff05-11e9-8242-17f96611fd05.png)


I've an issue that VSCode and Chrome are not highlighting the same line while de debugging. Of course the source of truth is Chrome. Anyway... I believe that's a separated issue. I had no need to add "debugger" to my code and upload it to server. I only added a breakpoint from VSCode and worked.

**Comment by simdax** [comment]
Just a comment:

The offset is due to some space left when loading the file. You can see the first three lines used by the async function loading

![image](https://user-images.githubusercontent.com/2458806/78436192-d7fb2380-7676-11ea-8263-4c0845dbea81.png)

So, to stay simple, just build you file starting with the script section, and an offset of two lines.

![image](https://user-images.githubusercontent.com/2458806/78436528-f06b3e00-7676-11ea-92d4-704be8fc94d0.png)

If someone has a better trick, like setting line offset in VSCode or Chrome ??
