### ISSUE TITLE
[Feature Request] Pass .vue file content directly to httpVueLoader()

### ISSUE THREAD

**Issue by danielfaust** [FranckFreiburger/http-vue-loader#72]
I would like to be able to load a component not from an url but from a string containing the vue file's content.

`const tComponent1 = httpVueLoader('./components/Component1.vue');`

vs

`const tComponent1 = httpVueLoader('<template>...</template>\n\n<script>...</script>\n\n<style>...</style>');`

This way the server could read the .vue file and embed it into the returned file, so that the browser doesn't have to fetch it over the network.

Is there any chance that this could get implemented?

**Comment by getflourish** [comment]
@danielfaust 

This is probably hacky, but you could override the `httpRequest` method and do something like that:

```
httpVueLoader.httpRequest = function(code) {
  return new Promise(function(resolve, reject) {
    resolve(code);
  })
};
   
const tComponent1 = httpVueLoader('<template>...</template>\n\n<script>...</script>\n\n<style>...</style>');

```

**Comment by danielfaust** [comment]
@getflourish I think that this will break the fetching of `src` attributes if they are present in a component.

https://github.com/FranckFreiburger/http-vue-loader/blob/cfb8b4148d532bc6b4ab2044168cc47d50f3168e/src/httpVueLoader.js#L286
