### ISSUE TITLE
Issue with Internet Explorer

### ISSUE THREAD

**Issue by littlephone** [FranckFreiburger/http-vue-loader#83]
Internet Explorer 10+ generates error on line 445 to line 446:
`
xhr.responseType = 'text'; 
xhr.open('GET', url); 
`
It is working fine if the above two lines were reversed:
`
 xhr.open('GET', url);  
xhr.responseType = 'text'; 
`
Anyone has the same issue ?

**Comment by arte0s** [comment]
I had the same error in IE11 and just comment line 445:
`//xhr.responseType = 'text';`
Everything started to work fine...

**Comment by lucatacconi** [comment]
Tested reversing order of lines xhr.open('GET', url); xhr.responseType = 'text'; 
It seems fixed on IE11. Thanks to @littlephone  and https://github.com/mhaderman
