### ISSUE TITLE
import an external ESM module inside a .vue file

### ISSUE THREAD

**Issue by nestarz** [FranckFreiburger/http-vue-loader#84]
Hello 👋

I would like to import an ESM module from my SFC vue file.
But require with absolute url and ES6 import doesn't work at all.

Is there any method to achieve it ?

Thanks for your work !
🙏

**Comment by nestarz** [comment]
Ok, for now I'm using this

```
module.exports = {
  components: {
    composableMap: async () => {
      const { ComposableMap } = await import(
        "http://localhost:63622/dist/index.es.js"
      );
      return ComposableMap;
    },
    annotation: async () => {
      const { Annotation } = await import(
        "http://localhost:63622/dist/index.es.js"
      );
      return Annotation;
    }
  }
};
```

**Comment by jdelrue** [comment]
++ need this

**Comment by SharkFourSix** [comment]
> foo: async () => {
>       const { Foo } = await import(
>         "http://localhost:63622/dist/index.es.js"
>       );
>       return Foo;
>     }

Using this exactly this method and format, I get this error

![image](https://user-images.githubusercontent.com/18681730/208098953-ffe2c71f-66a4-423d-93ae-b9d05b9d3ba5.png)

Vanilla JS, no other libraries. Vue 2
