### ISSUE TITLE
support for nested components ?

### ISSUE THREAD

**Issue by ReneBoehm** [FranckFreiburger/http-vue-loader#9]
I'm just starting to learn vuejs and I've just come across your httpVueLoader. A great tool since it may solve a problem I have, because I can't use a build environment in production for some reasons. Does it support nested components within the component imported via httpVueLoader ?

**Comment by FranckFreiburger** [comment]
It is supposed to support such cases, please can you provide a simple example for this issue ?

**Comment by ReneBoehm** [comment]
Sorry, my fault. As I said, I just started to learn vuejs. I didn't export the nested components.

It works as expected :)
