### ISSUE TITLE
Testing with Vue 3 (Release Client)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [FranckFreiburger/http-vue-loader#97]
Vue 3 alpha was silently released as a means to test other projects (like Vue-Loader).

* https://unpkg.com/vue@3.0.0-alpha.0

It will likely still have some changes before it is officially released (not an alpha or beta).

So testing of http-vue-loader against Vue 3 could potentially start now, if people are interested.

**Comment by hansroh** [comment]
Way interest.

But I think it will be late for starting from beta or statbe release.

**Comment by TheJaredWilcurt** [comment]
Here is a functioning JSFiddle with (currently) latest version of Vue 3 (alpha 7).

* https://jsfiddle.net/g9c0jpv7/1/

To make it easier for you to experiment with.

@hansroh

**Comment by TheJaredWilcurt** [comment]
Update, Beta 14

* https://jsfiddle.net/2vsdrx4p/

**Comment by danielfaust** [comment]
Hi @FranckFreiburger, now that Vue.js 3.0 is in its Release Candidate-state, would it be possible for you to adapt this loader? It's a mistery to me how this script does what it's able to do.

**Comment by dmikam** [comment]
Is it planned to support Vuejs3 an any visible future?

**Comment by FranckFreiburger** [comment]
support Vuejs3: yes
visible future: no

**Comment by FranckFreiburger** [comment]
dupe https://github.com/FranckFreiburger/http-vue-loader/issues/121
