### ISSUE TITLE
Why Example code fail to work?

### ISSUE THREAD

**Issue by BurningUnder** [FranckFreiburger/http-vue-loader#99]
I'm using example code and it fails to work, 

here is the folder:
![root](https://user-images.githubusercontent.com/31271647/72152955-79136e80-33e7-11ea-9dfd-f216ba776e53.png)

here is the bug report(when I open the index.html from folder using chrome:
![bug1](https://user-images.githubusercontent.com/31271647/72153265-63527900-33e8-11ea-8b6c-642ea4294147.png)
![bug2](https://user-images.githubusercontent.com/31271647/72153264-63527900-33e8-11ea-9ae4-2ef590e4d9a5.png)

here is the code(copy from the example):
```html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://unpkg.com/vue"></script>
    <script src="https://unpkg.com/http-vue-loader"></script>
  </head>

  <body>
    <div id="my-app">
      <my-component></my-component>
    </div>

    <script type="text/javascript">
      new Vue({
        el: '#my-app',
        components: {
          'my-component': httpVueLoader('my-component.vue')
        }
      });
    </script>
  </body>
</html>
```
```javascript
<template>
    <div class="hello">Hello {{who}}</div>
</template>

<script>
module.exports = {
    data: function() {
        return {
            who: 'world'
        }
    }
}
</script>

<style>
.hello {
    background-color: #ffe;
}
</style>
```

**Comment by BurningUnder** [comment]
It's fixed , sorry that I didn't see this,I using Chrome 79.0.3945.117ver
![fix](https://user-images.githubusercontent.com/31271647/72164977-ab31ca00-3401-11ea-848f-0d36cf2e2b26.png)

**Comment by BurningUnder** [comment]
maybe someone will forget this too, so I reopen it

**Comment by xiongmao86** [comment]
Is a webserver really optional? Since you have to run express to get vue component loaded?
